# Generated by Django 3.0.5 on 2020-04-23 06:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 4, 23, 6, 15, 28, 8287, tzinfo=utc), verbose_name='date_joined'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
